apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openfilter-pipelines-controller.fullname" . }}
  labels:
    {{- include "openfilter-pipelines-controller.labels" . | nindent 4 }}
    control-plane: controller-manager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openfilter-pipelines-controller.selectorLabels" . | nindent 6 }}
      control-plane: controller-manager
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openfilter-pipelines-controller.labels" . | nindent 8 }}
        control-plane: controller-manager
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openfilter-pipelines-controller.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: manager
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          args:
            {{- if .Values.controller.leaderElection.enabled }}
            - --leader-elect
            {{- end }}
            {{- if .Values.controller.metrics.enabled }}
            - --metrics-bind-address=:{{ .Values.controller.metrics.port }}
            {{- if .Values.controller.metrics.secureServing }}
            - --metrics-secure
            {{- end }}
            {{- end }}
            - --health-probe-bind-address=:{{ .Values.controller.health.port }}
            {{- with .Values.args }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            {{- if .Values.controller.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.controller.metrics.port }}
              protocol: TCP
            {{- end }}
            - name: health
              containerPort: {{ .Values.controller.health.port }}
              protocol: TCP
            {{- if .Values.controller.webhook.enabled }}
            - name: webhook
              containerPort: {{ .Values.controller.webhook.port }}
              protocol: TCP
            {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.volumeMounts .Values.controller.webhook.enabled }}
          volumeMounts:
            {{- if .Values.controller.webhook.enabled }}
            - name: cert
              mountPath: {{ .Values.controller.webhook.certDir }}
              readOnly: true
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          env:
            {{- if .Values.valkey.enabled }}
            - name: VALKEY_ADDR
              value: {{ include "openfilter-pipelines-controller.fullname" . }}-valkey-primary:6379
            {{- if .Values.valkey.auth.enabled }}
            - name: VALKEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "openfilter-pipelines-controller.fullname" . }}-valkey
                  key: valkey-password
            {{- end }}
            {{- end }}
            {{- if .Values.valkey.externalValkey.enabled }}
            - name: VALKEY_ADDR
              value: {{ .Values.valkey.externalValkey.host }}:{{ .Values.valkey.externalValkey.port }}
            {{- if .Values.valkey.externalValkey.password }}
            - name: VALKEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.valkey.externalValkey.existingSecret }}
                  key: {{ .Values.valkey.externalValkey.existingSecretPasswordKey }}
            {{- end }}
            {{- end }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- if or .Values.volumes .Values.controller.webhook.enabled }}
      volumes:
        {{- if .Values.controller.webhook.enabled }}
        - name: cert
          secret:
            secretName: {{ include "openfilter-pipelines-controller.fullname" . }}-webhook-cert
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
