apiVersion: filter.plainsight.ai/v1alpha1
kind: PipelineRun
metadata:
  name: pipelinerun-stream-sg
spec:
  pipelineRef:
    name: pipeline-rtsp-sg
  source:
    rtsp:
      host: camera.example.com
      port: 554
      path: /stream1
