apiVersion: filter.plainsight.ai/v1alpha1
kind: PipelineRun
metadata:
  labels:
    app.kubernetes.io/name: openfilter-pipelines-controller
    app.kubernetes.io/managed-by: kustomize
  # name: pipelinerun-sample
  generateName: pipelinerun-sample-
spec:
  pipelineRef:
    name: pipeline-sample
  source:
    bucket:
      name: cow-demo-development
      prefix: videos
      endpoint: storage.googleapis.com
      credentialsSecret:
        name: gcs-credentials
  execution:
    parallelism: 1
    maxAttempts: 3
    pendingTimeout: "5m"
